import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Apple iPhone 13",
    price: 62900,
    categoryName: "Mobile",
    rating: 4.7,
    features: [
      "iOS 15 Operating System",
      "5G Supported",
      "Apple A15 Bionic Chipset",
      "6.1-inch OLED Display",
      "128 GB Internal Memory",
      "Dual 12MP Primary Camera",
      "12 MP Front Camera",
      "1 Year Manufacturer Warranty",
    ],
  },
  {
    _id: uuid(),
    title: "Apple iPhone 14",
    price: 83490,
    categoryName: "Mobile",
    rating: 4.5,
    features: [
      "iOS 16 Operating System",
      "Apple A15 Bionic chip",
      "256 GB Internal Memory",
      "6.1-inch OLED Display",
      "Dual 12MP Primary Camera",
      "12 MP Front Camera",
      "Emergency SOS",
      "Crash Detection",
      "1 Year Manufacturer Warranty",
    ],
  },
  {
    _id: uuid(),
    title: "OnePlus 10 Pro 5G",
    price: 60999,
    categoryName: "Mobile",
    rating: 2.5,
    features: [
      "OxygenOS based on Android™12",
      "6.7 inches (17.02 cm) 120Hz Fluid AMOLED with LTPO Display",
      "Snapdragon 8 Gen 1 Mobile Platform",
      "GPU: Adreno 730",
      "8GB LPDDR5",
      "128GB UFS 3.1 2-LANE",
      "5,000 mAh Battery",
      "80W SUPERVOOC Charging",
      "1 Year Manufacturer Warranty",
    ],
  },
  {
    _id: uuid(),
    title: "Samsung Galaxy S22 5G",
    price: 66999,
    categoryName: "Mobile",
    rating: 3.5,
    features: [
      "OxygenOS based on Android™12",
      "6.7 inches (17.02 cm) 120Hz Fluid AMOLED with LTPO Display",
      "Snapdragon 8 Gen 1 Mobile Platform",
      "GPU: Adreno 730",
      "8GB LPDDR5",
      "128GB UFS 3.1 2-LANE",
      "5,000 mAh Battery",
      "80W SUPERVOOC Charging",
      "1 Year Manufacturer Warranty",
    ],
  },
  {
    _id: uuid(),
    title: "Asus TUF Gaming A15",
    price: 64999,
    categoryName: "Laptop",
    rating: 4.2,
    features: [
      "OxygenOS based on Android™12",
      "6.7 inches (17.02 cm) 120Hz Fluid AMOLED with LTPO Display",
      "Snapdragon 8 Gen 1 Mobile Platform",
      "GPU: Adreno 730",
      "8GB LPDDR5",
      "128GB UFS 3.1 2-LANE",
      "5,000 mAh Battery",
      "80W SUPERVOOC Charging",
      "1 Year Manufacturer Warranty",
    ],
  },
  {
    _id: uuid(),
    title: "Dell Inspiron 3511",
    price: 44999,
    categoryName: "Laptop",
    rating: 3.7,
    features: [
      "OxygenOS based on Android™12",
      "6.7 inches (17.02 cm) 120Hz Fluid AMOLED with LTPO Display",
      "Snapdragon 8 Gen 1 Mobile Platform",
      "GPU: Adreno 730",
      "8GB LPDDR5",
      "128GB UFS 3.1 2-LANE",
      "5,000 mAh Battery",
      "80W SUPERVOOC Charging",
      "1 Year Manufacturer Warranty",
    ],
  },
  {
    _id: uuid(),
    title: "Lenovo IdeaPad Flex 5",
    price: 66999,
    categoryName: "Laptop",
    rating: 1.6,
    features: [
      "OxygenOS based on Android™12",
      "6.7 inches (17.02 cm) 120Hz Fluid AMOLED with LTPO Display",
      "Snapdragon 8 Gen 1 Mobile Platform",
      "GPU: Adreno 730",
      "8GB LPDDR5",
      "128GB UFS 3.1 2-LANE",
      "5,000 mAh Battery",
      "80W SUPERVOOC Charging",
      "1 Year Manufacturer Warranty",
    ],
  },
  {
    _id: uuid(),
    title: "HP Pavilion x360 2-in-1",
    price: 57999,
    categoryName: "Laptop",
    rating: 2.9,
    features: [
      "OxygenOS based on Android™12",
      "6.7 inches (17.02 cm) 120Hz Fluid AMOLED with LTPO Display",
      "Snapdragon 8 Gen 1 Mobile Platform",
      "GPU: Adreno 730",
      "8GB LPDDR5",
      "128GB UFS 3.1 2-LANE",
      "5,000 mAh Battery",
      "80W SUPERVOOC Charging",
      "1 Year Manufacturer Warranty",
    ],
  },
  {
    _id: uuid(),
    title: "Samsung 108 cm (43 inches) Series 5",
    price: 31612,
    categoryName: "Television",
    rating: 3.9,
    features: [
      "OxygenOS based on Android™12",
      "6.7 inches (17.02 cm) 120Hz Fluid AMOLED with LTPO Display",
      "Snapdragon 8 Gen 1 Mobile Platform",
      "GPU: Adreno 730",
      "8GB LPDDR5",
      "128GB UFS 3.1 2-LANE",
      "5,000 mAh Battery",
      "80W SUPERVOOC Charging",
      "1 Year Manufacturer Warranty",
    ],
  },
  {
    _id: uuid(),
    title: "Sony 108 cm (43 inches) W830K HD Smart Tv",
    price: 40840,
    categoryName: "Television",
    rating: 4.6,
    features: [
      "OxygenOS based on Android™12",
      "6.7 inches (17.02 cm) 120Hz Fluid AMOLED with LTPO Display",
      "Snapdragon 8 Gen 1 Mobile Platform",
      "GPU: Adreno 730",
      "8GB LPDDR5",
      "128GB UFS 3.1 2-LANE",
      "5,000 mAh Battery",
      "80W SUPERVOOC Charging",
      "1 Year Manufacturer Warranty",
    ],
  },
  {
    _id: uuid(),
    title: "OnePlus 32 (80cm) 32Y1S Edge HD",
    price: 13999,
    categoryName: "Television",
    rating: 2.8,
    features: [
      "OxygenOS based on Android™12",
      "6.7 inches (17.02 cm) 120Hz Fluid AMOLED with LTPO Display",
      "Snapdragon 8 Gen 1 Mobile Platform",
      "GPU: Adreno 730",
      "8GB LPDDR5",
      "128GB UFS 3.1 2-LANE",
      "5,000 mAh Battery",
      "80W SUPERVOOC Charging",
      "1 Year Manufacturer Warranty",
    ],
  },
  {
    _id: uuid(),
    title: "LG 80 cm (32 inches) LQ63 HD Smart LED TV",
    price: 23270,
    categoryName: "Television",
    rating: 3.8,
    features: [
      "OxygenOS based on Android™12",
      "6.7 inches (17.02 cm) 120Hz Fluid AMOLED with LTPO Display",
      "Snapdragon 8 Gen 1 Mobile Platform",
      "GPU: Adreno 730",
      "8GB LPDDR5",
      "128GB UFS 3.1 2-LANE",
      "5,000 mAh Battery",
      "80W SUPERVOOC Charging",
      "1 Year Manufacturer Warranty",
    ],
  },
  {
    _id: uuid(),
    title: "HyperX Alloy Origins Core Tenkeyless Mechanical Gaming Keyboard",
    price: 7457,
    categoryName: "Accessories",
    rating: 4.1,
    features: [
      "OxygenOS based on Android™12",
      "6.7 inches (17.02 cm) 120Hz Fluid AMOLED with LTPO Display",
      "Snapdragon 8 Gen 1 Mobile Platform",
      "GPU: Adreno 730",
      "8GB LPDDR5",
      "128GB UFS 3.1 2-LANE",
      "5,000 mAh Battery",
      "80W SUPERVOOC Charging",
      "1 Year Manufacturer Warranty",
    ],
  },
  {
    _id: uuid(),
    title: "Lenovo 300 Wireless Compact Mouse, High Resolution 1000 DPI",
    price: 749,
    categoryName: "Accessories",
    rating: 3.6,
    features: [
      "OxygenOS based on Android™12",
      "6.7 inches (17.02 cm) 120Hz Fluid AMOLED with LTPO Display",
      "Snapdragon 8 Gen 1 Mobile Platform",
      "GPU: Adreno 730",
      "8GB LPDDR5",
      "128GB UFS 3.1 2-LANE",
      "5,000 mAh Battery",
      "80W SUPERVOOC Charging",
      "1 Year Manufacturer Warranty",
    ],
  },
  {
    _id: uuid(),
    title: "Apple MagSafe Charger",
    price: 3999,
    categoryName: "Accessories",
    rating: 4.8,
    features: [
      "OxygenOS based on Android™12",
      "6.7 inches (17.02 cm) 120Hz Fluid AMOLED with LTPO Display",
      "Snapdragon 8 Gen 1 Mobile Platform",
      "GPU: Adreno 730",
      "8GB LPDDR5",
      "128GB UFS 3.1 2-LANE",
      "5,000 mAh Battery",
      "80W SUPERVOOC Charging",
      "1 Year Manufacturer Warranty",
    ],
  },
];
